### ISSUE TITLE
ARadar integration

### ISSUE THREAD

**Issue by cagnulein** [kartoone/mybiketraffic#6]
Hi @kartoone I just discovered your project and I found it awesome (I was thinking to build something similar too before discovering it!)
So in the past days I created ARadar, a standalone app for Apple Watch and Garmin Varia https://robertoviola.cloud/2022/05/27/garmin-varia-on-apple-watch-finally/

It will be nice to integrate it together with your project.
If I saw it correctly, I just need to export a fit file with the developer items from the radar, isn't it?

What do you think?

**Comment by kartoone** [comment]
Wow, that is amazing, I was hoping to do something similar with an iOS phone app, but hadn't made it very far yet. Yes, the fit file is what my site needs to get the data. You have to add the following DeveloperFields for full compatibility with these first five fields are all "RECORD" messages meaning they are stored every second:  radar_ranges (signed two byte int for all 8 vehicles), radar_speeds (unsigned 1 byte int for all 8 vehicles), radar_current (unsigned two byte int, total count up to that point), passing_speed (unsigned 1 byte int, the measured relative speed of just the closest vehicle), passing_speedabs (unsigned 1 byte int, the calculated absolute speed relative plus rider speed).

The next field radar_total is an unsigned 2 byte int for the total vehicle count stored as a session field.

The final field radar_lap is the total number of cars that passed on a given lap and is stored with each lap.

I've also attached a picture of the relevant part of the code from MyBikeTrafficFitContributions.mc

<img width="731" alt="Screen Shot 2022-05-27 at 9 46 21 AM" src="https://user-images.githubusercontent.com/2796475/170725394-0ea52fb7-5395-45cc-8d40-c42816b5634f.png">

I'm about to leave to race the Tour Divide so I won't be able to work much on this until I get back in July. But feel free to ask me questions here or via direct email brtoone@samford.edu and I will try to get back to you if I'm able.

**Comment by cagnulein** [comment]
Thanks! What a nice trip the Tour Divide! I will follow you on Strava if you have it!
About this project, do you have something to auto upload the fit file? It would be very nice since i'm collecting a lot of informations every day on my zones!

**Comment by cagnulein** [comment]
@kartoone i'm developing this in these days. Fit file is almost ready, i will attach here a sample just to validate it.

**Comment by cagnulein** [comment]
@kartoone done, i just need how to upload automatically the file to  your server. Let me know!

**Comment by kartoone** [comment]
I haven’t gotten the auto-upload working yet. That’s a process that only works through Garmin Connect, and I have to add a script that a user can run to authorize the auto-upload. Definitely on the “to do” list!

From: Roberto Viola ***@***.***>
Date: Thursday, July 7, 2022 at 7:54 AM
To: kartoone/mybiketraffic ***@***.***>
Cc: Toone, Brian ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL]Re: [kartoone/mybiketraffic] ARadar integration (Issue #6)

@kartoone<https://secure-web.cisco.com/1vMWIzTmiTQO3YwxN_2WdNE4icseEsl86WsLYUo8a7w2KCjGcSqPers9JO7X0qxecVnNxLWE2pDEJYo1_6VJEFEHlMYYmOVvNokbvydyt2oqXFo6DkSte64Z01ASoQlVoKOO7liOY5L8UrJOs56v81SrllrfEpZofQqBFfHYtm0T4cmBLLL72_CY3IGrY00l4PVmNkKqaRh04Ttk5_VXNWI3B4TnFePIFpfHtJsn3QMqs6rnl8s0UzMxaqUBs_asZ45w5jT2EutCmoiHBxR2xLYUrzobNoRhfeMFAB7674LdwA95Ji5QKTaEhMsJa8YJt/https%3A%2F%2Fgithub.com%2Fkartoone> done, i just need how to upload automatically the file to your server. Let me know!

**Comment by cagnulein** [comment]
hah ok, good to know!
If you have a sample file I can check if my integration is 100% compatible 
I tried to upload a file on your website but i found a lot of php errors 
Let me know

**Comment by cagnulein** [comment]
hi @kartoone I hope your trip went ok! Can you upload a sample file from your app so I can match it to mine?

My app is working ok but i would like to add the compatibility to your portal  

https://user-images.githubusercontent.com/48216/180928404-40cc2c9d-b8c5-4654-bbb5-1b152c9e5435.MOV

**Comment by kartoone** [comment]
Sorry for the delay in getting back to you, the trip was amazing ... here is a sample FIT file ... let me know if you have any issues decoding it to see the individual records. I believe there are RECORD messages as well as LAP messages as well as SESSION messages to look for. I went ahead and uploaded that FIT file to my account and here is the corresponding ride: https://www.mybiketraffic.com/rides/view/25403
[2022-07-08-17-32-18.fit.zip](https://github.com/kartoone/mybiketraffic/files/9190586/2022-07-08-17-32-18.fit.zip)

**Comment by cagnulein** [comment]
Great! Thanks for the file
While i'm comparing them, this is a file from aradar

[1658835969.079585.zip](https://github.com/kartoone/mybiketraffic/files/9190701/1658835969.079585.zip)

**Comment by cagnulein** [comment]
These are the errors that I got from your site when I try to import it

A PHP Error was encountered
Severity: Warning

Message: unlink(/var/www/mybiketraffic/uploads/3544/): Is a directory

Filename: models/Rides_model.php

Line Number: 385

Backtrace:

File: /var/www/mybiketraffic/application/models/Rides_model.php
Line: 385
Function: unlink

File: /var/www/mybiketraffic/application/controllers/Rides.php
Line: 301
Function: import

File: /var/www/mybiketraffic/index.php
Line: 315
Function: require_once

A PHP Error was encountered
Severity: Notice

Message: Trying to access array offset on value of type bool

Filename: controllers/Rides.php

Line Number: 302

Backtrace:

File: /var/www/mybiketraffic/application/controllers/Rides.php
Line: 302
Function: _error_handler

File: /var/www/mybiketraffic/index.php
Line: 315
Function: require_once

**Comment by kartoone** [comment]
Thanks the most common reason for that specific error is trying to upload a ZIP file instead of a .FIT file. Try unzipping/extract the file first and uploading it directly.

**Comment by cagnulein** [comment]
@kartoone nope, it was the fit file directly

**Comment by cagnulein** [comment]
@kartoone did you try this one https://github.com/kartoone/mybiketraffic/files/9190701/1658835969.079585.zip (unzipping it of course ;) ) ?

**Comment by kartoone** [comment]
Thanks for the update, my apologies, I’ve seen that error before and assumed this was the reason but upon further investigation, I am getting the same error you were. I’m going to investigate more today and will get back to you ASAP.

Brian Toone, PhD
Mathematics and Computer Science
205-726-2960<tel:+1205-726-2960> | office
***@***.******@***.***>
http://cs.briantoone.com
800 Lakeshore Drive
Birmingham, AL 35229<https://maps.google.com/maps?q=800+Lakeshore+Drive,+Birmingham,+AL+35229,+US>


From: Roberto Viola ***@***.***>
Date: Friday, September 2, 2022 at 8:21 AM
To: kartoone/mybiketraffic ***@***.***>
Cc: Toone, Brian ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL]Re: [kartoone/mybiketraffic] ARadar integration (Issue #6)
This email originated from outside of Samford University. Please consider carefully whether you should click on any links, open any attachments, or provide any information.


@kartoone<https://secure-web.cisco.com/18fxk_X3S6h3aEV78fOC2JjuWaJ2tOEwvBEOSa8txqfcFRUnCvK7xYDyGJReGx7W0AgYM6KcJtxOhBOGOgApEoupNdI8Pw0_d6tn5Tq15NdWBULco_OEuUKZKpktP5VLDYDB-JGuSDFDQOSBr1GzMAM2KC9RYIebm39SU39gmNZT1w5bA-gA-lk13zXNSipj0QTu-rmTBGxnJM9-Arb5nBycnPuXzdXHWI9iCUzNqN5k7Hb60TlR07zXj6okfyutlm6U8oLR1DthR7RkQ_3nSypu7HsZ2JvozI_0twS7DaSisAGr_8TJMKjEGEuEyhmRY/https%3A%2F%2Fgithub.com%2Fkartoone> did you try this one https://github.com/kartoone/mybiketraffic/files/9190701/1658835969.079585.zip<https://secure-web.cisco.com/1xwxM3iceRLlJLZDOsx-O6zC-HhYa8-JdN5tPeygiAIG9OhPyrNpboSkOACb735EFSEfb4Oj7uvQ4bl3vp1eA1qcXf4PSvPfrnCl__7nqwGldkumlZo8qrClXP2jwchk5TnlB9PUs_OCnGjbrMcJXekYQUaBvOcpF-aqEEiget_uwoRxUpvM4QtmEwrY5RjLql3FHYK-wykb7wHTlh8pX5j_NOwXD_O2IOse-paMmw_U_s1W3FmAwxRXjcrsHCnXbWpldBx90VCYVDCHLos07aIvbXlAaL5ss_7aVXjecvQIz_Qh411JKcDLfVDgjrUp6/https%3A%2F%2Fgithub.com%2Fkartoone%2Fmybiketraffic%2Ffiles%2F9190701%2F1658835969.079585.zip> (unzipping it of course ;) ) ?

**Comment by kartoone** [comment]
Should be all fixed now. Try uploading that FIT file again.

From: Toone, Brian ***@***.***>
Date: Friday, September 2, 2022 at 8:28 AM
To: kartoone/mybiketraffic ***@***.***>
Subject: Re: [EXTERNAL]Re: [kartoone/mybiketraffic] ARadar integration (Issue #6)
Thanks for the update, my apologies, I’ve seen that error before and assumed this was the reason but upon further investigation, I am getting the same error you were. I’m going to investigate more today and will get back to you ASAP.

Brian Toone, PhD
Mathematics and Computer Science
205-726-2960<tel:+1205-726-2960> | office
***@***.******@***.***>
http://cs.briantoone.com
800 Lakeshore Drive
Birmingham, AL 35229<https://maps.google.com/maps?q=800+Lakeshore+Drive,+Birmingham,+AL+35229,+US>


From: Roberto Viola ***@***.***>
Date: Friday, September 2, 2022 at 8:21 AM
To: kartoone/mybiketraffic ***@***.***>
Cc: Toone, Brian ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL]Re: [kartoone/mybiketraffic] ARadar integration (Issue #6)
This email originated from outside of Samford University. Please consider carefully whether you should click on any links, open any attachments, or provide any information.


@kartoone<https://secure-web.cisco.com/18fxk_X3S6h3aEV78fOC2JjuWaJ2tOEwvBEOSa8txqfcFRUnCvK7xYDyGJReGx7W0AgYM6KcJtxOhBOGOgApEoupNdI8Pw0_d6tn5Tq15NdWBULco_OEuUKZKpktP5VLDYDB-JGuSDFDQOSBr1GzMAM2KC9RYIebm39SU39gmNZT1w5bA-gA-lk13zXNSipj0QTu-rmTBGxnJM9-Arb5nBycnPuXzdXHWI9iCUzNqN5k7Hb60TlR07zXj6okfyutlm6U8oLR1DthR7RkQ_3nSypu7HsZ2JvozI_0twS7DaSisAGr_8TJMKjEGEuEyhmRY/https%3A%2F%2Fgithub.com%2Fkartoone> did you try this one https://github.com/kartoone/mybiketraffic/files/9190701/1658835969.079585.zip<https://secure-web.cisco.com/1xwxM3iceRLlJLZDOsx-O6zC-HhYa8-JdN5tPeygiAIG9OhPyrNpboSkOACb735EFSEfb4Oj7uvQ4bl3vp1eA1qcXf4PSvPfrnCl__7nqwGldkumlZo8qrClXP2jwchk5TnlB9PUs_OCnGjbrMcJXekYQUaBvOcpF-aqEEiget_uwoRxUpvM4QtmEwrY5RjLql3FHYK-wykb7wHTlh8pX5j_NOwXD_O2IOse-paMmw_U_s1W3FmAwxRXjcrsHCnXbWpldBx90VCYVDCHLos07aIvbXlAaL5ss_7aVXjecvQIz_Qh411JKcDLfVDgjrUp6/https%3A%2F%2Fgithub.com%2Fkartoone%2Fmybiketraffic%2Ffiles%2F9190701%2F1658835969.079585.zip> (unzipping it of course ;) ) ?

**Comment by cagnulein** [comment]
@kartoone The upload process now starts but I'm still seeing this errors

A PHP Error was encountered
Severity: Warning

Message: unlink(/var/www/mybiketraffic/uploads/3544/): Is a directory

Filename: models/Rides_model.php

Line Number: 402

Backtrace:

File: /var/www/mybiketraffic/application/models/Rides_model.php
Line: 402
Function: unlink

File: /var/www/mybiketraffic/application/controllers/Rides.php
Line: 328
Function: import

File: /var/www/mybiketraffic/index.php
Line: 315
Function: require_once

A PHP Error was encountered
Severity: Notice

Message: Trying to access array offset on value of type bool

Filename: controllers/Rides.php

Line Number: 329

Backtrace:

File: /var/www/mybiketraffic/application/controllers/Rides.php
Line: 329
Function: _error_handler

File: /var/www/mybiketraffic/index.php
Line: 315
Function: require_once


I had to delete the previous file in order to upload it again (same file used)

**Comment by kartoone** [comment]
Ah, yes, I had manually renamed your FIT file to take out the extra “.” in the filename before uploading it. I’ve fixed the site now so that it can handle filenames with an extra “.” somewhere in the filename. Try one more time and let me know if you are still getting that error. Also, many thanks for helping me track down this problem.

Thanks,
Brian

From: Roberto Viola ***@***.***>
Date: Saturday, September 3, 2022 at 12:23 AM
To: kartoone/mybiketraffic ***@***.***>
Cc: Toone, Brian ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL]Re: [kartoone/mybiketraffic] ARadar integration (Issue #6)
This email originated from outside of Samford University. Please consider carefully whether you should click on any links, open any attachments, or provide any information.


@kartoone<https://secure-web.cisco.com/1WXS3Is6uWP4Uhl52qEFg-VGy97LGwVpceltKy_hsPz3y8qiHW4JYApMKFs_4MeJLdRt-ZtSfGPZkX-zoK7J6kdGHusjxoKN3_mtuo8vmzfFmhggVaJLBxTNi0l2uGWn7iIgA167MSzdCGbn3D-eJ_Oiy1PSSdS5CbQqiWfTNPWi4lBPv_TqJNJ6v3e66-2hNEIX4vX1PU1J5i7qn539Cv5dD6l5CpZKaBsW-CblAA0XSq9AbUvOHQNw25DU4UxXp3kwJjZCbMHq0sk_L_HgwjYdhVKvkTgzjiI1WH9QEqT2NF6BowceMqzvU3woY4FuA/https%3A%2F%2Fgithub.com%2Fkartoone> The upload process now starts but I'm still seeing this errors

A PHP Error was encountered
Severity: Warning

Message: unlink(/var/www/mybiketraffic/uploads/3544/): Is a directory

Filename: models/Rides_model.php

Line Number: 402

Backtrace:

File: /var/www/mybiketraffic/application/models/Rides_model.php
Line: 402
Function: unlink

File: /var/www/mybiketraffic/application/controllers/Rides.php
Line: 328
Function: import

File: /var/www/mybiketraffic/index.php
Line: 315
Function: require_once

A PHP Error was encountered
Severity: Notice

Message: Trying to access array offset on value of type bool

Filename: controllers/Rides.php

Line Number: 329

Backtrace:

File: /var/www/mybiketraffic/application/controllers/Rides.php
Line: 329
Function: _error_handler

File: /var/www/mybiketraffic/index.php
Line: 315
Function: require_once

I had to delete the previous file in order to upload it again (same file used)

**Comment by cagnulein** [comment]
hi @kartoone sorry to be a pain, but I had the same error

A PHP Error was encountered
Severity: Notice

Message: Undefined variable: user_id

Filename: controllers/Rides.php

Line Number: 329

Backtrace:

File: /var/www/mybiketraffic/application/controllers/Rides.php
Line: 329
Function: _error_handler

File: /var/www/mybiketraffic/index.php
Line: 315
Function: require_once

A PHP Error was encountered
Severity: Notice

Message: Undefined index: extension

Filename: models/Rides_model.php

Line Number: 386

Backtrace:

File: /var/www/mybiketraffic/application/models/Rides_model.php
Line: 386
Function: _error_handler

File: /var/www/mybiketraffic/application/controllers/Rides.php
Line: 329
Function: import

File: /var/www/mybiketraffic/index.php
Line: 315
Function: require_once

A PHP Error was encountered
Severity: Notice

Message: Trying to access array offset on value of type bool

Filename: controllers/Rides.php

Line Number: 330

Backtrace:

File: /var/www/mybiketraffic/application/controllers/Rides.php
Line: 330
Function: _error_handler

File: /var/www/mybiketraffic/index.php
Line: 315
Function: require_once

**Comment by kartoone** [comment]
Try logging in again, if you still had the screen open it may have logged you out without giving any indication, which is another problem I’d like to fix. It doesn’t keep you logged in for more than about 30 minutes to an hour. I was able to upload this file you emailed me without any errors or renaming it: 1658835969.079585.fit

From: Roberto Viola ***@***.***>
Date: Saturday, September 3, 2022 at 11:31 AM
To: kartoone/mybiketraffic ***@***.***>
Cc: Toone, Brian ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL]Re: [kartoone/mybiketraffic] ARadar integration (Issue #6)
This email originated from outside of Samford University. Please consider carefully whether you should click on any links, open any attachments, or provide any information.


hi @kartoone<https://secure-web.cisco.com/1P-eiRHklRs78qVvV8tJ_fvPcR5kW-CdrroFFzPZCb57fkNsXAvVKTpk3AI-KtBTyAnG7LZKQzJyOFyK07uKsFTUonkXRg3layTJO64wvf3kmUAkPqkYpjlZfxJ7A_r9w_doLNiAT7koooghd4WEBNb3qlPS0q_5yAccWM7mWON0SJoCkCulNJCysPdHIxv-5kLRp2A_xLjdZtbkbfGxvYqNs19hrZcR2ZO6ZF8GsU4XSsQFxnyCQBwHpbMiQ-cZwYDuGuotLBSeVZvjSa8_icgZUbj7yILTpR4CSad5Ant9FaFkjErsLEbuoFoUHLwGU/https%3A%2F%2Fgithub.com%2Fkartoone> sorry to be a pain, but I had the same error

A PHP Error was encountered
Severity: Notice

Message: Undefined variable: user_id

Filename: controllers/Rides.php

Line Number: 329

Backtrace:

File: /var/www/mybiketraffic/application/controllers/Rides.php
Line: 329
Function: _error_handler

File: /var/www/mybiketraffic/index.php
Line: 315
Function: require_once

A PHP Error was encountered
Severity: Notice

Message: Undefined index: extension

Filename: models/Rides_model.php

Line Number: 386

Backtrace:

File: /var/www/mybiketraffic/application/models/Rides_model.php
Line: 386
Function: _error_handler

File: /var/www/mybiketraffic/application/controllers/Rides.php
Line: 329
Function: import

File: /var/www/mybiketraffic/index.php
Line: 315
Function: require_once

A PHP Error was encountered
Severity: Notice

Message: Trying to access array offset on value of type bool

Filename: controllers/Rides.php

Line Number: 330

Backtrace:

File: /var/www/mybiketraffic/application/controllers/Rides.php
Line: 330
Function: _error_handler

File: /var/www/mybiketraffic/index.php
Line: 315
Function: require_once

**Comment by kartoone** [comment]
Also, do you have JavaScript disabled for the site? Even if you are able to get the import to work, you won’t be able to view the ride without javascript enabled. The reason why I ask is it looks like you manually clicked the “upload” button which you should only have to do if you have javascript disabled. Otherwise, it should upload automatically once you select one or more files. Much of the website depends on JavaScript being enabled.  Brian

From: Toone, Brian ***@***.***>
Date: Saturday, September 3, 2022 at 3:59 PM
To: kartoone/mybiketraffic ***@***.***>
Subject: Re: [EXTERNAL]Re: [kartoone/mybiketraffic] ARadar integration (Issue #6)
Try logging in again, if you still had the screen open it may have logged you out without giving any indication, which is another problem I’d like to fix. It doesn’t keep you logged in for more than about 30 minutes to an hour. I was able to upload this file you emailed me without any errors or renaming it: 1658835969.079585.fit

From: Roberto Viola ***@***.***>
Date: Saturday, September 3, 2022 at 11:31 AM
To: kartoone/mybiketraffic ***@***.***>
Cc: Toone, Brian ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL]Re: [kartoone/mybiketraffic] ARadar integration (Issue #6)
This email originated from outside of Samford University. Please consider carefully whether you should click on any links, open any attachments, or provide any information.


hi @kartoone<https://secure-web.cisco.com/1P-eiRHklRs78qVvV8tJ_fvPcR5kW-CdrroFFzPZCb57fkNsXAvVKTpk3AI-KtBTyAnG7LZKQzJyOFyK07uKsFTUonkXRg3layTJO64wvf3kmUAkPqkYpjlZfxJ7A_r9w_doLNiAT7koooghd4WEBNb3qlPS0q_5yAccWM7mWON0SJoCkCulNJCysPdHIxv-5kLRp2A_xLjdZtbkbfGxvYqNs19hrZcR2ZO6ZF8GsU4XSsQFxnyCQBwHpbMiQ-cZwYDuGuotLBSeVZvjSa8_icgZUbj7yILTpR4CSad5Ant9FaFkjErsLEbuoFoUHLwGU/https%3A%2F%2Fgithub.com%2Fkartoone> sorry to be a pain, but I had the same error

A PHP Error was encountered
Severity: Notice

Message: Undefined variable: user_id

Filename: controllers/Rides.php

Line Number: 329

Backtrace:

File: /var/www/mybiketraffic/application/controllers/Rides.php
Line: 329
Function: _error_handler

File: /var/www/mybiketraffic/index.php
Line: 315
Function: require_once

A PHP Error was encountered
Severity: Notice

Message: Undefined index: extension

Filename: models/Rides_model.php

Line Number: 386

Backtrace:

File: /var/www/mybiketraffic/application/models/Rides_model.php
Line: 386
Function: _error_handler

File: /var/www/mybiketraffic/application/controllers/Rides.php
Line: 329
Function: import

File: /var/www/mybiketraffic/index.php
Line: 315
Function: require_once

A PHP Error was encountered
Severity: Notice

Message: Trying to access array offset on value of type bool

Filename: controllers/Rides.php

Line Number: 330

Backtrace:

File: /var/www/mybiketraffic/application/controllers/Rides.php
Line: 330
Function: _error_handler

File: /var/www/mybiketraffic/index.php
Line: 315
Function: require_once

**Comment by cagnulein** [comment]
@kartoone i'm using Chrome on MacOS on M1. Javascript enabled. I logged out and log in it back. Same result. It parses the file, I saw the stats, but when i press the upload button it's always print that errors.
I'm selecting metric unit if it matters.

It's not a big deal for me, I'm using Aradar for browsing my ride, so no hurry from me :)

**Comment by kartoone** [comment]
Ah, now I understand. Once you see the stats, the ride is already uploaded. There is no need to click the upload button. You can see the uploaded rides by clicking “Your Rides” in the menu at the top and the ride should be there. I have just updated the UI on that page to make it clearer and add a direct link to the ride from the upload page.

From: Roberto Viola ***@***.***>
Date: Monday, September 5, 2022 at 1:32 AM
To: kartoone/mybiketraffic ***@***.***>
Cc: Toone, Brian ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL]Re: [kartoone/mybiketraffic] ARadar integration (Issue #6)
This email originated from outside of Samford University. Please consider carefully whether you should click on any links, open any attachments, or provide any information.


@kartoone<https://secure-web.cisco.com/1NmVhsvCBSxw5ILrlnefhCYncMx9xkF2os82MFxioSCgnfhlnhnVYsDN9BUMmG_OiGX60U424KzjvgKmay_MWIy68BimB8KSl2taseQA8ucgbCHucn3JmBRYN8s6USLXib5EyztMRbS_6KKu5W2-h_vIFB4Ll4xTrDKxdlOBjy7tGTfX3JK9nZ3eMQsGKuXRttp2KeJjXLI1yBCSMFOggoxlZca4GMPXkVf3YiLU9qIo7mR42WoALhdEO2tCTWPHlUNPwpP4_QIvCTGhLU2ae1YStZ3OCDQ9ASSJ5V37fx47KEs0bmFkAw0soFK95ppe1/https%3A%2F%2Fgithub.com%2Fkartoone> i'm using Chrome on MacOS on M1. Javascript enabled. I logged out and log in it back. Same result. It parses the file, I saw the stats, but when i press the upload button it's always print that errors.
I'm selecting metric unit if it matters.

It's not a big deal for me, I'm using Aradar for browsing my ride, so no hurry from me :)

**Comment by cagnulein** [comment]
hah ok! So it was a stupid user error :D
I guess we can close this unless you want to keep this open for the upload API

**Comment by kartoone** [comment]
Nah, no such thing as a stupid user error, that just means the UI wasn’t clear enough. I could see how you might interpret it as a pre-processing step before the actual upload/import into your account. That upload button was how it worked before I added the drag/drop area. I kept it around because it enables compatibility with javascript disabled browsers, but you need javascript enabled for pretty much most of the site so I’ve just deleted the button. Also, yes, let’s keep the issue open as it will hopefully motivate me to get the auto-upload / sync to mybiketraffic finally implemented.

From: Roberto Viola ***@***.***>
Date: Monday, September 5, 2022 at 7:52 AM
To: kartoone/mybiketraffic ***@***.***>
Cc: Toone, Brian ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL]Re: [kartoone/mybiketraffic] ARadar integration (Issue #6)
This email originated from outside of Samford University. Please consider carefully whether you should click on any links, open any attachments, or provide any information.


hah ok! So it was a stupid user error :D
I guess we can close this unless you want to keep this open for the upload API

**Comment by kartoone** [comment]
Make sure you unzip it first?

From: Roberto Viola ***@***.***>
Date: Tuesday, July 26, 2022 at 9:44 AM
To: kartoone/mybiketraffic ***@***.***>
Cc: Toone, Brian ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL]Re: [kartoone/mybiketraffic] ARadar integration (Issue #6)

These are the errors that I got from your site when I try to import it

A PHP Error was encountered
Severity: Warning

Message: unlink(/var/www/mybiketraffic/uploads/3544/): Is a directory

Filename: models/Rides_model.php

Line Number: 385

Backtrace:

File: /var/www/mybiketraffic/application/models/Rides_model.php
Line: 385
Function: unlink

File: /var/www/mybiketraffic/application/controllers/Rides.php
Line: 301
Function: import

File: /var/www/mybiketraffic/index.php
Line: 315
Function: require_once

A PHP Error was encountered
Severity: Notice

Message: Trying to access array offset on value of type bool

Filename: controllers/Rides.php

Line Number: 302

Backtrace:

File: /var/www/mybiketraffic/application/controllers/Rides.php
Line: 302
Function: _error_handler

File: /var/www/mybiketraffic/index.php
Line: 315
Function: require_once

**Comment by cagnulein** [comment]
@kartoone i guess Github is going crazy today. I'm receiving a lot of notifications from the past!

**Comment by kartoone** [comment]
I know it's been a few years now, but I do have OAUTH integration enabled if you want your users to be able to contribute their data directly from your ARadar watch app. Let me know and I can get you setup with the oauth info you'll need to use.

**Comment by cagnulein** [comment]
Sure it will be great! If wou want you can send me the instructions to
Roberto.viola83 at Gmail.com

Let me know


Roberto Viola

I sometimes trade time with my daughter to help. If this was valuable,
please support my time:
https://buymeacoffee.com/cagnulein
https://www.patreon.com/cagnulein/join
https://paypal.me/cagnulein

Software engineer and open source enthusiast, QZ Creator
http://robertoviola.cloud
http://qzfitness.com/

Il giorno mer 2 set 2026 alle 19:55 Brian Toone ***@***.***>
ha scritto:
